# Generated by Django 3.1.4 on 2020-12-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
                ('dob', models.CharField(default='', max_length=10)),
                ('phone', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=15)),
                ('state', models.CharField(default='', max_length=15)),
                ('country', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
